### ISSUE TITLE
Does this guide work for machine with legacy/BIOS instead of EFI?

### ISSUE THREAD

**Issue by extricator** [Broly1/Hackintosh-linux-Installer#2]
First off, thanks for this guide, very appreciated since there doesn't seem to be an "official" entrypoint from anything other than OSX. I want to turn an old "backup" laptop of mine into OSx86 for development purposes but the laptop doesn't have EFI, just a plain old BIOS.

**Comment by Broly1** [comment]
No it doesn't unfortunately, you may find what you are looking for at Hackintosh paradise on discord https://discord.gg/kWAzHGN
