### ISSUE TITLE
ERROR: E_FAIL

### ISSUE THREAD

**Issue by voltangle** [Broly1/Hackintosh-linux-Installer#3]
Wanted to use this tool to make my flash drive. Nope, does not work. It returns the E_FAIL error.
How can I fix it?

Failed when extracting the .pkg

**Comment by Broly1** [comment]
What linux  distribution are you using and what kernel also what version of macos are you downloading, I'll take a look at it tomorrow.

**Comment by voltangle** [comment]
I am downloading Catalina 10.15.7 on Ubuntu 20.04.1 Live USB. Idk about the kernel version

**Comment by Broly1** [comment]
Strange I use the same disturb recently and it worked fine which script are you trying to use ?but if yoi are in a hurry you can use the manual guide below

**Comment by voltangle** [comment]
I am using gibMacOS + finalflash. And yes, ill try the manual guide

**Comment by voltangle** [comment]
I tried. Something gone wrong
Opencore does not sees my flash drive, i cant boot from it
What is interesting, that the filesystem detected is Unknown by GParted

**Comment by Broly1** [comment]
I have similar error when I give the wrong path for that script you can't  drag an drop the PKG to the the terminal but the directory containing it, the other scrip tribeam is much simpler it does everything all in one.

**Comment by voltangle** [comment]
I'll try tribeam. I think I screwed up the manual tutorial

**Comment by voltangle** [comment]
Well, it also failed. 

```
WARNING!!! SELECTING THE WRONG DISK MAY WIPE YOUR PC AND ALL DATA!!!
Please select the usb-drive!!
1) sda   238.5G
2) sdb    15.1G
3) sdc   116.2G
#? 3
Disk sdc will be erased do you wish to continue [y/n] ? y

umount: /dev/sdc1: not mounted.
umount: /dev/sdc2: not mounted.
GPT data structures destroyed! You may now partition the disk using fdisk or
other utilities.
Warning: The driver descriptor says the physical block size is 2048 bytes, but Linux says it is 512 bytes.
```

**Comment by voltangle** [comment]
What is also bad, that today i am going to a trip, and I need to fix my hackintosh ASAP, because there will be or no internet, or that bad, that you will download 100MB file for A HALF OF AN OUR. I need to fix it now)

P.S. This is in Ukraine

**Comment by voltangle** [comment]
> I have similar error when I give the wrong path for that script you can't drag an drop the PKG to the the terminal but the directory containing it, the other scrip tribeam is much simpler it does everything all in one.

Well, i was talking about the manual guide

**Comment by voltangle** [comment]
Wait, the EFI partition needs to be first partition, or not?

**Comment by voltangle** [comment]
And i think i know what was the issue with gibMacOS + finalflash. I had no more space left on my USB :)
EDIT: And also with tribeam :)
EDIT2: Nope, that wasnt the issue with tribeam. It still fails there.

**Comment by voltangle** [comment]
```
Please paste the recovery pkg path to extract:macOS-Downloads/publicrelease/catalina 
extracting RecoveryHDMetaDmg.pkg...
ERROR: Data Error : RecoveryHDMeta.dmg
```
Are you kidding me? Why is everything failing?)

**Comment by voltangle** [comment]
I tried to combine Dortania's guide and your's. Now GParted sees that macOS partition is HFS+. Now we need to paste our EFI, change the flags, and i will try :)

UPDATE: Nope, it has not worked.
And yes, what is the error with tribeam, why does it stop flashing?

**Comment by Broly1** [comment]
the issue with tribeam seems to be  a dd command issue, try manually formatting the usb drive before running the script.

**Comment by voltangle** [comment]
okay, ill try
I will send an update when im finished

**Comment by Broly1** [comment]
![Screenshot from 2020-10-24 11-48-37](https://user-images.githubusercontent.com/6778968/97086060-13e3df00-15ef-11eb-813c-fb603a1f6597.png)
I've successfully made the installer

**Comment by voltangle** [comment]
Hmm
Idk why it works on your machine, bu on mine it is broken. Anyways, I haven't needed USB installer, I just needed to update OpenCore to 0.6.3 nightly build XD
